name: Kernel CI

on:
  push:
    branches:
      - lineage-18.1-rebase
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        ref: 'lineage-18.1-github-actions'

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache
        sudo git clone --depth 1 --branch lineage-17.1 --single-branch https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 /opt/toolchains/arm-linux-androideabi-4.9/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=lifehackerhansol
        export KBUILD_BUILD_HOST=lifehackerhansol-android
        make -j22 ARCH=arm VARIANT_DEFCONFIG=jf_eur_defconfig jf_defconfig
        make -j128
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/zImage /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
